### ISSUE TITLE
Bundling .less files without compilation?

### ISSUE THREAD

**Issue by MoonStorm** [HuasoFoundries/systemjs-less-plugin#13]
I've been trying to bundle up the ``.less`` files contained in the ``bootstrap-less`` package, with no success so far. For example the command ``jspm bundle bootstrap-less/bootstrap/index.less! dist/external-deps-bootstrap.js``, seems to compile the bootstrap less files. However, for dev purposes, if a ``.less`` file in the app references any ``.less`` file from bootstrap, all the ``.less`` files get downloaded again.  Is it possible to ignore the compilation of these files but still bundle them? Would then a a second config be required to be referenced from the app in order to perform the compilation in the browser?

The config is below:
```
SystemJS.config({
  paths: {
    "github:": "jspm_packages/github/",
    "npm:": "jspm_packages/npm/",
    "web-client/": "ClientSrc/",
  },
  devConfig: {
  transpiler: "plugin-typescript",
  typescriptOptions: {
    "tsconfig": true
  },
  packages: {
    "web-client": {
      "main": "modules/main.dev.ts",
      "defaultExtension": "ts",
      "meta": {
        "*.ts": {
          "loader": "plugin-typescript"
        },
        "*.less": {
          "loader": "less"
        },
        "*.css": {
          "loader": "less"
        }
      }
    }
  },
 [... mappings ,etc.]
});
```
Any help would be appreciated. Thanks.

**Comment by ffflabs** [comment]
When using `bundle` (as opposed to a static build), bundled files are referenced by their original path. If a mixin or referenced less file is requested from inside the main less file by a name which isn't said path, I'm afraid it will be considered a different file.

This means that, since less uses relative paths, and bundles use mapped paths with exclamation mark, they won't match.

You might force the bundling of these files using minimatch format:

```sh
jspm bundle bootstrap-less/bootstrap/index.less + bootstrap-less/bootstrap/**/*.less dist/external-deps-bootstrap.js
```

**Comment by ffflabs** [comment]
@MoonStorm perhaps the merge of #17 could help you with this issue

**Comment by MoonStorm** [comment]
Brilliant, thanks for making me aware of it. I'll give it a shot.
